<a href="https://colab.research.google.com/github/heygalaxya/ml-score-de-credito/blob/main/Previs%C3%A3o_de_Score_de_Cr%C3%A9dito_dos_Clientes_(heygalaxya).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Inteligência Artificial e Previsões

Score de Crédito dos Clientes

Você foi contratado por um banco para conseguir definir o score de crédito dos clientes. Você precisa analisar todos os clientes do banco e, com base nessa análise, criar um modelo que consiga ler as informações do cliente e dizer automaticamente o score de crédito dele: Ruim, Ok, Bom.

In [ ]:
#%% 0 - INSTALAR AS BIBLIOTECAS
!pip install pandas
!pip install scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [ ]:
#%% 1 - IMPORTAR A BASE DE DADOS

In [ ]:
import pandas as pd

df = pd.read_csv('clientes.csv')
display(df)

       id_cliente  mes  ...  emprestimo_credito emprestimo_estudantil
0            3392    1  ...                   1                     0
1            3392    2  ...                   1                     0
2            3392    3  ...                   1                     0
3            3392    4  ...                   1                     0
4            3392    5  ...                   1                     0
...           ...  ...  ...                 ...                   ...
99995       37932    4  ...                   0                     1
99996       37932    5  ...                   0                     1
99997       37932    6  ...                   0                     1
99998       37932    7  ...                   0                     1
99999       37932    8  ...                   0                     1

[100000 rows x 25 columns]

In [ ]:
#%% 2 - VISUALIZAR A BASE DE DADOS
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  object
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  object
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  object
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(7), object(4)
memory usage: 19.1+ MB

None

In [ ]:
#%% 3 - TRATAMENTO DOS DADOS

In [ ]:
df = df.drop(columns='id_cliente')

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
codificador_profissao = LabelEncoder()
df['profissao'] = codificador_profissao.fit_transform(df['profissao'])

codificador_mix = LabelEncoder()
df['mix_credito'] = codificador_mix.fit_transform(df['mix_credito'])

codificador_comportamento = LabelEncoder()
df['comportamento_pagamento'] = codificador_comportamento.fit_transform(df['comportamento_pagamento'])

display(df)

       mes  idade  ...  emprestimo_credito  emprestimo_estudantil
0        1   23.0  ...                   1                      0
1        2   23.0  ...                   1                      0
2        3   23.0  ...                   1                      0
3        4   23.0  ...                   1                      0
4        5   23.0  ...                   1                      0
...    ...    ...  ...                 ...                    ...
99995    4   25.0  ...                   0                      1
99996    5   25.0  ...                   0                      1
99997    6   25.0  ...                   0                      1
99998    7   25.0  ...                   0                      1
99999    8   25.0  ...                   0                      1

[100000 rows x 24 columns]

In [ ]:
#%% 4. TREINAMENTO DA IA
y = df['score_credito']
x = df.drop(columns='score_credito')

In [ ]:
#visualizando as colunas para observar se ha linhas vazias, se tem algum tipo de dado a ser tratado
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 24 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   mes                       100000 non-null  int64
 1   idade                     100000 non-null  float64
 2   profissao                 100000 non-null  int64
 3   salario_anual             100000 non-null  float64
 4   num_contas                100000 non-null  float64
 5   num_cartoes               100000 non-null  float64
 6   juros_emprestimo          100000 non-null  float64
 7   num_emprestimos           100000 non-null  float64
 8   dias_atraso               100000 non-null  float64
 9   num_pagamentos_atrasados  100000 non-null  float64
 10  num_verificacoes_credito  100000 non-null  float64
 11  mix_credito               100000 non-null  int64
 12  divida_total              100000 non-null  float64
 13  taxa_uso_credito          100000 non-null  float64
 14  idade_historico_credito   100000 non-null  float64
 15  investimento_mensal       100000 non-null  float64
 16  comportamento_pagamento   100000 non-null  int64
 17  saldo_final_mes           100000 non-null  float64
 18  score_credito             100000 non-null  object
 19  emprestimo_carro          100000 non-null  int64
 20  emprestimo_casa           100000 non-null  int64
 21  emprestimo_pessoal        100000 non-null  int64
 22  emprestimo_credito        100000 non-null  int64
 23  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(9), object(1)
memory usage: 18.3+ MB

None

In [ ]:
# campos de treino e de teste
from sklearn.model_selection import train_test_split

# test_size=0.3 -> esse parametro indica que 30% dos dados serao separados para teste e os 70% serao para treino
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3)

In [ ]:
# modelo de previsao -> se score esta bom, ruim ou ok
# 1 - importar a IA (modelo)
#modelo 1
from sklearn.ensemble import RandomForestClassifier
#modelo 2
from sklearn.neighbors import KNeighborsClassifier

# 2 - criar a IA (modelo)
#modelo 1
modelo_arvoredecisao = RandomForestClassifier()
#modelo 2
modelo_knn = KNeighborsClassifier()

# 3 - treinar a IA (modelo)
#modelo 1
modelo_arvoredecisao.fit(x_treino, y_treino)
#modelo 2
modelo_knn.fit(x_treino, y_treino)

KNeighborsClassifier()

In [ ]:
#%% 5. TESTE PARA ESCOLHA DO MELHOR MODELO DE PREVISAO

In [ ]:
from sklearn.metrics import accuracy_score
# Avaliar e escolher o melhor modelo de previsao

#modelo 1
previsao_arvore = modelo_arvoredecisao.predict(x_teste)
#modelo 2
previsao_knn = modelo_knn.predict(x_teste)

# comparar a previsao com o y_teste
from sklearn.metrics import accuracy_score

display(accuracy_score(y_teste, previsao_arvore))
display(accuracy_score(y_teste, previsao_knn))

0.8245

0.7346

In [ ]:
# O MELHOR MODELO E A ARVORE DE DECISAO

In [ ]:
# NOVAS PREVISOES

novos_clientes = pd.read_csv('novos_clientes.csv')

display(novos_clientes)
display(novos_clientes.info())

   mes  idade  ... emprestimo_credito  emprestimo_estudantil
0    1   31.0  ...                  0                      0
1    4   32.0  ...                  0                      1
2    2   48.0  ...                  1                      0

[3 rows x 23 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   mes                       3 non-null      int64
 1   idade                     3 non-null      float64
 2   profissao                 3 non-null      object
 3   salario_anual             3 non-null      float64
 4   num_contas                3 non-null      float64
 5   num_cartoes               3 non-null      float64
 6   juros_emprestimo          3 non-null      float64
 7   num_emprestimos           3 non-null      float64
 8   dias_atraso               3 non-null      float64
 9   num_pagamentos_atrasados  3 non-null      float64
 10  num_verificacoes_credito  3 non-null      float64
 11  mix_credito               3 non-null      object
 12  divida_total              3 non-null      float64
 13  taxa_uso_credito          3 non-null      float64
 14  idade_historico_credito   3 non-null      float64
 15  investimento_mensal       3 non-null      float64
 16  comportamento_pagamento   3 non-null      object
 17  saldo_final_mes           3 non-null      float64
 18  emprestimo_carro          3 non-null      int64
 19  emprestimo_casa           3 non-null      int64
 20  emprestimo_pessoal        3 non-null      int64
 21  emprestimo_credito        3 non-null      int64
 22  emprestimo_estudantil     3 non-null      int64
dtypes: float64(14), int64(6), object(3)
memory usage: 684.0+ bytes

None

In [ ]:
# FAZENDO O TRATAMENTO DOS DADOS DO NOVO ARQUIVO PARA TESTE

novos_clientes['profissao'] = codificador_profissao.transform(novos_clientes['profissao'])

novos_clientes['mix_credito'] = codificador_mix.transform(novos_clientes['mix_credito'])

novos_clientes['comportamento_pagamento'] = codificador_comportamento.transform(novos_clientes['comportamento_pagamento'])

#%% 6. FAZER AS NOVAS PREVISOES
previsao = modelo_arvoredecisao.predict(novos_clientes)

display(novos_clientes)
display(previsao)

   mes  idade  ...  emprestimo_credito  emprestimo_estudantil
0    1   31.0  ...                   0                      0
1    4   32.0  ...                   0                      1
2    2   48.0  ...                   1                      0

[3 rows x 23 columns]

array(['Poor', 'Poor', 'Standard'], dtype=object)